# Generated by Django 4.1.4 on 2023-01-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_events_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecs',
            name='production_year',
            field=models.IntegerField(),
        ),
    ]
