# Generated by Django 4.1.4 on 2023-01-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_events_api', '0002_carspecs_car_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecs',
            name='production_year',
            field=models.IntegerField(max_length=20),
        ),
    ]
