# Generated by Django 4.1.4 on 2023-01-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_events_api', '0003_alter_carspecs_production_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecs',
            name='car_plan',
        ),
    ]
