# Generated by Django 4.1.4 on 2023-01-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_events_api', '0005_alter_carspecs_production_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspecs',
            name='car_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_events_api.carplan'),
        ),
    ]
