# Generated by Django 4.1.4 on 2023-01-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_events_api', '0006_carspecs_car_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carspecs',
            old_name='car_brand',
            new_name='car_make',
        ),
    ]
