# Generated by Django 4.1.4 on 2023-01-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_events_api', '0007_rename_car_brand_carspecs_car_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecs',
            name='car_plan',
        ),
        migrations.AddField(
            model_name='carplan',
            name='car_specs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='car_events_api.carspecs'),
        ),
    ]
