# Generated by Django 4.1.4 on 2023-01-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_events_api', '0008_remove_carspecs_car_plan_carplan_car_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carplan',
            name='car_specs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='car_events_api.carspecs'),
        ),
    ]
